/**
 * Seed script: 20 realistic intake submissions.
 *
 * Run: npx tsx scripts/seed-intakes.ts
 *
 * Creates diverse submissions across industries, service types,
 * complexity levels, and detail levels. The analyzeIntake() engine
 * auto-generates all scoring and recommendations.
 */

import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
import { drizzle } from "drizzle-orm/node-postgres";
import { Pool } from "pg";
import * as schema from "../src/lib/schema";
import { analyzeIntake } from "../src/lib/intake-scoring";
import type { IntakeFormData } from "../src/types/intake";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const db = drizzle(pool, { schema });

// ---------------------------------------------------------------------------
// 20 Mock Intakes
// ---------------------------------------------------------------------------

const intakes: IntakeFormData[] = [
  // 1. Precision Plumbing — local plumber, marketing website
  {
    selectedServices: ["marketing-website"],
    name: "Marcus Thompson",
    email: "marcus@precisionplumbing.com",
    phone: "305-555-0142",
    company: "Precision Plumbing Co",
    industry: "home-services",
    businessSize: "6-20",
    website: "precisionplumbingmiami.com",
    yearsInBusiness: "6-10",
    serviceAnswers: {
      "marketing-website": {
        primaryOffering: "Full-service residential and commercial plumbing — emergency repairs, water heater installation, drain cleaning, pipe replacement, bathroom/kitchen remodels. We serve all of Miami-Dade and Broward counties.",
        targetAudience: "Homeowners aged 30-60 in Miami-Dade and Broward counties. Also property managers and commercial building owners who need reliable, licensed plumbers on call.",
        primaryCta: "call",
        pageEstimate: "4-7",
        contentReady: "some",
        blogNeeded: "yes-occasional",
        integrations: ["google-analytics", "google-business", "booking"],
        seoFocus: "local",
        testimonialsReviews: "yes-many",
        competitorUrls: "roto-rooter.com — too corporate. We want the local trust factor.\njohntheplumber.com — clean, simple. We like this direction.",
      },
    },
    timeline: "1-3-months",
    budgetRange: "5k-15k",
    designPreference: "professional",
    hasBrandAssets: "yes-partial",
    brandColors: "Navy blue and white. Our trucks are already wrapped in this color scheme.",
    competitorSites: "roto-rooter.com, miamiplumber247.com",
    inspirationSites: "johntherooter.com — clean and trustworthy feel",
    additionalNotes: "We get most of our business from Google right now but our current site looks like it was built in 2012. We need something that makes us look as professional as we are. We have about 200 Google reviews at 4.8 stars.",
    howDidYouHear: "google-search",
    preferredContact: "phone",
  },

  // 2. Atlas Law Group — law firm, website + CRM
  {
    selectedServices: ["marketing-website", "crm-system"],
    name: "Victoria Chen",
    email: "vchen@atlaslawgroup.com",
    phone: "212-555-0198",
    company: "Atlas Law Group",
    industry: "professional-services",
    businessSize: "6-20",
    website: "atlaslawgroup.com",
    yearsInBusiness: "10+",
    serviceAnswers: {
      "marketing-website": {
        primaryOffering: "Corporate law, mergers & acquisitions, intellectual property litigation, and startup advisory. We serve mid-market companies and venture-backed startups across the Northeast.",
        targetAudience: "CEOs, CFOs, and general counsel at companies with $5M-$200M revenue. Also founders of Series A-C startups who need sophisticated legal counsel without Big Law pricing.",
        primaryCta: "form",
        pageEstimate: "8-15",
        contentReady: "some",
        blogNeeded: "yes-regular",
        integrations: ["google-analytics", "email-marketing", "chat"],
        seoFocus: "specific-keywords",
        testimonialsReviews: "yes-few",
        competitorUrls: "cooley.com — great practice area pages\nfenwick.com — modern feel for a law firm",
      },
      "crm-system": {
        currentProcess: ["spreadsheets", "email", "existing-crm"],
        contactVolume: "201-1000",
        pipelineStages: "Prospect → Initial Consultation → Engagement Letter Sent → Retained → Active Matter → Closed → Alumni (for future referrals)",
        crmFeatures: ["pipeline", "notes", "email-integration", "tasks", "reporting"],
        crmIntegrations: ["email-provider", "calendar", "accounting"],
        teamSize: "6-15",
        automationNeeds: "Automated follow-ups after initial consultations. Reminder emails when engagement letters go unsigned for 48+ hours. Monthly client relationship check-ins. Matter deadline tracking.",
      },
    },
    timeline: "3-6-months",
    budgetRange: "15k-30k",
    designPreference: "elegant",
    hasBrandAssets: "yes-full",
    brandColors: "Deep charcoal, gold accents, and white. Very refined and premium.",
    competitorSites: "cooley.com, fenwick.com, wilsonlegal.com",
    inspirationSites: "stripe.com — the clarity and modernity. We want to be the Stripe of law firms.",
    additionalNotes: "We're currently on an old WordPress site and using Clio for case management, but our business development pipeline is managed in spreadsheets. We need a unified system. Our managing partners want something that looks as premium as our hourly rate.",
    howDidYouHear: "referral",
    preferredContact: "email",
  },

  // 3. Bloom & Brew Cafe — small cafe, website redesign, tight budget
  {
    selectedServices: ["website-redesign"],
    name: "Jamie Rodriguez",
    email: "jamie@bloomandbrew.com",
    phone: "",
    company: "Bloom & Brew Cafe",
    industry: "food-hospitality",
    businessSize: "1-5",
    website: "bloomandbrew.squarespace.com",
    yearsInBusiness: "1-2",
    serviceAnswers: {
      "website-redesign": {
        currentSiteUrl: "https://bloomandbrew.squarespace.com",
        currentPlatform: "squarespace",
        dislikesCurrent: "It looks generic. Every other coffee shop has the same Squarespace template. We can't customize the online ordering integration the way we want, and the menu page is clunky on mobile.",
        keepFromCurrent: "Our photos are good. We invested in a professional shoot last month.",
        topVisitorProblems: "Menu doesn't load properly on phones, can't find our hours easily, no way to order ahead.",
        keepContent: "keep-some",
        analyticsData: "no",
        newFeatures: "Online ordering for pickup, weekly specials section that's easy to update, Instagram feed integration",
      },
    },
    timeline: "1-3-months",
    budgetRange: "1k-5k",
    designPreference: "warm",
    hasBrandAssets: "yes-partial",
    brandColors: "Sage green, cream, and warm brown. Earthy and inviting.",
    competitorSites: "blueBottlecoffee.com",
    inspirationSites: "",
    additionalNotes: "We're a neighborhood cafe and we want our website to feel like walking into our shop — warm, inviting, personal.",
    howDidYouHear: "social-media",
    preferredContact: "email",
  },

  // 4. Summit Fitness — gym, website + client portal
  {
    selectedServices: ["marketing-website", "client-portal"],
    name: "Derek Okafor",
    email: "derek@summitfitnessstudio.com",
    phone: "404-555-0176",
    company: "Summit Fitness Studio",
    industry: "fitness-wellness",
    businessSize: "6-20",
    website: "summitfitnessstudio.com",
    yearsInBusiness: "3-5",
    serviceAnswers: {
      "marketing-website": {
        primaryOffering: "Boutique fitness studio offering personal training, group HIIT classes, yoga, and nutrition coaching. We also sell branded merchandise and meal prep plans.",
        targetAudience: "Health-conscious professionals aged 25-45 in the Buckhead area of Atlanta. Dual income, willing to invest $200+/month in fitness.",
        primaryCta: "book",
        pageEstimate: "4-7",
        contentReady: "no",
        blogNeeded: "yes-regular",
        integrations: ["google-analytics", "booking", "payment", "social"],
        seoFocus: "local",
        testimonialsReviews: "yes-many",
        competitorUrls: "orangetheory.com — great energy\nbarry's.com — premium feel",
      },
      "client-portal": {
        portalPurpose: ["project-status", "appointments", "invoices", "documents"],
        currentClientComm: ["email", "phone", "social"],
        documentSharing: "yes-download-only",
        paymentPortal: "yes",
        activeClientCount: "51-200",
        portalBranding: "branded",
        portalIntegrations: "Mindbody for class scheduling, Stripe for payments, and we'd love to integrate with MyFitnessPal or similar for nutrition tracking.",
      },
    },
    timeline: "1-3-months",
    budgetRange: "5k-15k",
    designPreference: "bold",
    hasBrandAssets: "yes-full",
    brandColors: "Electric orange and charcoal black. High energy.",
    competitorSites: "orangetheory.com, barrys.com, soulcycle.com",
    inspirationSites: "peloton.com — their digital experience is what we want for our brand",
    additionalNotes: "We've grown from 50 to 180 active members in 2 years and our current website doesn't reflect who we are now. Members keep asking for an app or portal where they can book classes, see their progress, and manage their membership. We want to reduce the admin time we spend on scheduling and billing.",
    howDidYouHear: "referral",
    preferredContact: "phone",
  },

  // 5. GreenLeaf Landscaping — simple landing page
  {
    selectedServices: ["landing-page"],
    name: "Carlos Mendez",
    email: "carlos@greenleaflandscaping.com",
    phone: "832-555-0134",
    company: "GreenLeaf Landscaping",
    industry: "home-services",
    businessSize: "1-5",
    website: "",
    yearsInBusiness: "1-2",
    serviceAnswers: {
      "landing-page": {
        offerDescription: "Spring lawn renovation packages — full lawn aeration, overseeding, fertilization, and first mow included. Starting at $299 for lawns up to 5,000 sq ft.",
        desiredAction: "contact",
        trafficSource: ["facebook-ads", "social-organic"],
        existingFunnel: "no",
        uniqueValue: "We're fully licensed, insured, and use only organic products. 100% satisfaction guarantee or we'll redo the work free. Most competitors use harsh chemicals.",
        socialProof: ["reviews", "numbers"],
        abTesting: "later",
      },
    },
    timeline: "asap",
    budgetRange: "1k-5k",
    designPreference: "clean",
    hasBrandAssets: "no",
    brandColors: "",
    competitorSites: "",
    inspirationSites: "",
    additionalNotes: "Spring season is coming and I need this up fast. Running Facebook ads starting next month.",
    howDidYouHear: "google-search",
    preferredContact: "phone",
  },

  // 6. Nexus Tech Solutions — enterprise, full platform + AI
  {
    selectedServices: ["full-platform", "ai-tools", "business-dashboard"],
    name: "Sarah Kim",
    email: "sarah.kim@nexustechsolutions.io",
    phone: "415-555-0211",
    company: "Nexus Tech Solutions",
    industry: "technology",
    businessSize: "21-50",
    website: "nexustechsolutions.io",
    yearsInBusiness: "6-10",
    serviceAnswers: {
      "full-platform": {
        businessProcesses: ["client-management", "project-tracking", "invoicing", "team-management", "reporting", "communication"],
        platformTeamSize: "21-50",
        currentTools: "Jira for project tracking, Salesforce for CRM (way too expensive), QuickBooks for invoicing, Slack for comms, Google Sheets for capacity planning and resource allocation. It's a nightmare of disconnected tools.",
        biggestPainPoint: "We spend 15+ hours per week reconciling data across systems. Our project profitability reports take 3 days to compile because data lives in 5 different tools. We've outgrown our toolstack and need a unified platform.",
        clientFacing: "yes-essential",
        billingNeeds: ["create-invoices", "online-payment", "recurring", "estimates", "accounting-sync"],
        automationPriorities: "Client onboarding workflow (currently 23 manual steps), weekly project status reports, invoice generation from tracked time, capacity planning alerts when team utilization exceeds 85%.",
        migrationData: "yes-lots",
      },
      "ai-tools": {
        aiTaskDescription: "Two AI use cases: (1) Intelligent project estimation — feed in scope documents and get time/cost estimates based on our historical data. (2) Automated weekly client status reports generated from project tracking data.",
        aiDataSource: ["text-documents", "customer-data", "financial"],
        aiUsers: ["internal-team"],
        aiErrorConsequence: "medium-risk",
        humanReview: "always",
        aiIntegrations: "Should integrate directly with the project tracking and CRM modules of the platform. Also needs access to our historical project data for estimation model training.",
        aiVolume: "11-100",
      },
      "business-dashboard": {
        dashboardPurpose: "Executive visibility into company health — project profitability, team utilization, revenue pipeline, client satisfaction scores, and financial forecasting. Also per-project dashboards for PMs.",
        dashboardUsers: ["executives", "managers"],
        userCount: "6-20",
        dataSources: ["database", "api", "accounting"],
        keyMetrics: "Revenue per employee, project margin %, team utilization rate, average deal cycle time, monthly recurring revenue, client retention rate, time-to-delivery by project type.",
        rbacNeeded: "yes",
        mobileAccess: "nice-to-have",
        dataRefresh: "realtime",
        reportingExport: ["pdf-reports", "csv-export", "scheduled"],
      },
    },
    timeline: "3-6-months",
    budgetRange: "30k+",
    designPreference: "modern",
    hasBrandAssets: "yes-full",
    brandColors: "Deep purple (#6B21A8), white, and neon green accents. Tech-forward.",
    competitorSites: "linear.app, notion.so, monday.com",
    inspirationSites: "linear.app — best-in-class project management UX\nvercel.com — clean, developer-focused design language",
    additionalNotes: "We're a B2B software consultancy that's grown fast and our tools haven't kept up. We need a single platform that replaces Salesforce + Jira + our spreadsheet mess. Budget is flexible for the right solution — we're spending $4k/month on Salesforce alone. We want to see an ROI within 6 months.",
    howDidYouHear: "referral",
    preferredContact: "email",
  },

  // 7. Harmony Health Clinic — healthcare, portal + dashboard
  {
    selectedServices: ["client-portal", "business-dashboard"],
    name: "Dr. Amara Obi",
    email: "dr.obi@harmonyhealthclinic.com",
    phone: "770-555-0163",
    company: "Harmony Health Clinic",
    industry: "healthcare",
    businessSize: "6-20",
    website: "harmonyhealthclinic.com",
    yearsInBusiness: "3-5",
    serviceAnswers: {
      "client-portal": {
        portalPurpose: ["project-status", "documents", "messaging", "appointments", "reports"],
        currentClientComm: ["email", "phone", "in-person"],
        documentSharing: "yes-upload-download",
        paymentPortal: "yes",
        activeClientCount: "51-200",
        portalBranding: "branded",
        portalIntegrations: "Our EHR system (currently Jane App), insurance verification, lab result delivery, and Stripe for copay/self-pay collection.",
      },
      "business-dashboard": {
        dashboardPurpose: "Track patient volume, appointment utilization, revenue by service line, insurance claim status, and provider productivity metrics.",
        dashboardUsers: ["executives", "managers"],
        userCount: "1-5",
        dataSources: ["database", "api", "accounting"],
        keyMetrics: "Daily patient visits, revenue per provider, no-show rate, average wait time, insurance reimbursement cycle time, patient satisfaction scores.",
        rbacNeeded: "yes",
        mobileAccess: "critical",
        dataRefresh: "daily",
        reportingExport: ["pdf-reports", "csv-export"],
      },
    },
    timeline: "3-6-months",
    budgetRange: "15k-30k",
    designPreference: "calming",
    hasBrandAssets: "yes-full",
    brandColors: "Soft teal, white, and warm gray. Clinical but calming.",
    competitorSites: "",
    inspirationSites: "onemedical.com — patient experience feels modern and approachable",
    additionalNotes: "We're an integrative health clinic with 3 providers and growing. Our patients constantly ask for a way to message us, see their visit summaries, and pay bills online without calling. HIPAA compliance is mandatory for anything patient-facing.",
    howDidYouHear: "referral",
    preferredContact: "email",
  },

  // 8. Coastal Real Estate Group — website + CRM
  {
    selectedServices: ["marketing-website", "crm-system"],
    name: "Brandon Hayes",
    email: "brandon@coastalrealtygroup.com",
    phone: "843-555-0127",
    company: "Coastal Real Estate Group",
    industry: "real-estate",
    businessSize: "6-20",
    website: "coastalrealtygroup.com",
    yearsInBusiness: "10+",
    serviceAnswers: {
      "marketing-website": {
        primaryOffering: "Luxury residential real estate along the South Carolina coast — Charleston, Kiawah Island, Hilton Head. Listings from $500K to $5M+. We also do vacation rental management for 45 properties.",
        targetAudience: "High-net-worth individuals and families looking for primary residences or vacation homes on the SC coast. Ages 40-65, household income $300K+. Also investors looking for rental properties.",
        primaryCta: "form",
        pageEstimate: "15+",
        contentReady: "some",
        blogNeeded: "yes-regular",
        integrations: ["google-analytics", "google-business", "email-marketing", "crm", "chat"],
        seoFocus: "local",
        testimonialsReviews: "yes-many",
        competitorUrls: "danielravenel.com — luxury feel\ncharleston-realestate.com — good MLS integration",
      },
      "crm-system": {
        currentProcess: ["spreadsheets", "email", "phone-notes"],
        contactVolume: "201-1000",
        pipelineStages: "Inquiry → Showing Scheduled → Showing Complete → Offer Discussion → Under Contract → Inspection → Closing → Closed → Post-Sale Follow-Up",
        crmFeatures: ["pipeline", "notes", "email-integration", "tasks", "scheduling", "automation", "mobile"],
        crmIntegrations: ["email-provider", "calendar", "marketing"],
        teamSize: "6-15",
        automationNeeds: "Automated drip emails for leads based on property interest. Anniversary emails to past buyers. Listing alert notifications. Follow-up reminders after showings.",
      },
    },
    timeline: "1-3-months",
    budgetRange: "15k-30k",
    designPreference: "luxury",
    hasBrandAssets: "yes-full",
    brandColors: "Navy, gold, and white. Coastal luxury.",
    competitorSites: "danielravenel.com, charlestonfineliving.com",
    inspirationSites: "sothebysrealty.com — the gold standard for luxury real estate web presence",
    additionalNotes: "We just merged with another brokerage and went from 4 agents to 12. Our current site is WordPress and it's falling apart. We need IDX/MLS integration or at least a featured listings section. The CRM is critical — our agents are losing deals because leads fall through the cracks.",
    howDidYouHear: "google-search",
    preferredContact: "phone",
  },

  // 9. Bright Minds Academy — education, website + portal
  {
    selectedServices: ["marketing-website", "client-portal"],
    name: "Natasha Williams",
    email: "natasha@brightmindsacademy.org",
    phone: "678-555-0199",
    company: "Bright Minds Academy",
    industry: "education",
    businessSize: "6-20",
    website: "",
    yearsInBusiness: "1-2",
    serviceAnswers: {
      "marketing-website": {
        primaryOffering: "After-school STEM enrichment programs for K-8 students. Coding, robotics, science experiments, and math enrichment. In-person at 3 locations in Metro Atlanta and virtual programs available nationwide.",
        targetAudience: "Parents of school-aged children (K-8) in Metro Atlanta who value education and extracurriculars. Dual-income families, education-focused, want their kids to get ahead.",
        primaryCta: "book",
        pageEstimate: "4-7",
        contentReady: "no",
        blogNeeded: "yes-occasional",
        integrations: ["google-analytics", "booking", "payment", "email-marketing"],
        seoFocus: "local",
        testimonialsReviews: "yes-few",
        competitorUrls: "",
      },
      "client-portal": {
        portalPurpose: ["project-status", "documents", "invoices", "appointments"],
        currentClientComm: ["email", "phone", "social"],
        documentSharing: "yes-download-only",
        paymentPortal: "yes",
        activeClientCount: "51-200",
        portalBranding: "branded",
        portalIntegrations: "Stripe for tuition payments, Google Calendar for class schedules",
      },
    },
    timeline: "1-3-months",
    budgetRange: "5k-15k",
    designPreference: "fun",
    hasBrandAssets: "no",
    brandColors: "",
    competitorSites: "",
    inspirationSites: "codeninjas.com — fun, kid-friendly, but still professional for parents",
    additionalNotes: "We're growing fast and need to look professional for parents. Right now we take enrollment through Google Forms and it's embarrassing. Parents need to see schedules, pay tuition, and track their child's progress.",
    howDidYouHear: "social-media",
    preferredContact: "email",
  },

  // 10. Iron Wolf Construction — construction, marketing website
  {
    selectedServices: ["marketing-website"],
    name: "Dmitri Volkov",
    email: "dmitri@ironwolfconstruction.com",
    phone: "713-555-0145",
    company: "Iron Wolf Construction",
    industry: "construction",
    businessSize: "6-20",
    website: "",
    yearsInBusiness: "3-5",
    serviceAnswers: {
      "marketing-website": {
        primaryOffering: "General contracting — commercial tenant buildouts, restaurant renovations, and retail space construction. Licensed and insured, $1M-$10M projects.",
        targetAudience: "Commercial property owners, restaurant groups, and retail chains in the Greater Houston area looking for a reliable GC who delivers on time and on budget.",
        primaryCta: "form",
        pageEstimate: "4-7",
        contentReady: "no",
        blogNeeded: "no",
        integrations: ["google-analytics", "google-business"],
        seoFocus: "local",
        testimonialsReviews: "yes-few",
        competitorUrls: "",
      },
    },
    timeline: "1-3-months",
    budgetRange: "5k-15k",
    designPreference: "industrial",
    hasBrandAssets: "yes-partial",
    brandColors: "Black, steel gray, and orange accents.",
    competitorSites: "",
    inspirationSites: "",
    additionalNotes: "We get all our work through relationships right now but we need a web presence. Our competitors all have sites that show their projects. We have great project photos from the last 15 buildouts.",
    howDidYouHear: "referral",
    preferredContact: "phone",
  },

  // 11. Luna Beauty Lounge — website redesign, small budget
  {
    selectedServices: ["website-redesign"],
    name: "Sofia Reyes",
    email: "sofia@lunabeautylounge.com",
    phone: "786-555-0118",
    company: "Luna Beauty Lounge",
    industry: "fitness-wellness",
    businessSize: "1-5",
    website: "lunabeautylounge.com",
    yearsInBusiness: "1-2",
    serviceAnswers: {
      "website-redesign": {
        currentSiteUrl: "https://lunabeautylounge.com",
        currentPlatform: "wix",
        dislikesCurrent: "It looks cheap. The booking widget doesn't work half the time. My Instagram looks 10x better than my website.",
        keepFromCurrent: "My service list and pricing are accurate.",
        topVisitorProblems: "Can't book appointments reliably, slow loading, menu is confusing.",
        keepContent: "keep-some",
        analyticsData: "no",
        newFeatures: "Working booking system, before/after gallery, gift card purchasing",
      },
    },
    timeline: "asap",
    budgetRange: "1k-5k",
    designPreference: "glamorous",
    hasBrandAssets: "yes-partial",
    brandColors: "Rose gold, blush pink, and white.",
    competitorSites: "drybar.com",
    inspirationSites: "",
    additionalNotes: "I'm losing bookings because my Wix site is unreliable. I need this fixed quickly.",
    howDidYouHear: "instagram",
    preferredContact: "email",
  },

  // 12. Vertex Consulting — business dashboard
  {
    selectedServices: ["business-dashboard"],
    name: "Robert Park",
    email: "rpark@vertexconsulting.com",
    phone: "312-555-0167",
    company: "Vertex Consulting Group",
    industry: "professional-services",
    businessSize: "21-50",
    website: "vertexconsulting.com",
    yearsInBusiness: "10+",
    serviceAnswers: {
      "business-dashboard": {
        dashboardPurpose: "Centralized view of consulting engagement profitability, consultant utilization rates, sales pipeline health, and financial forecasting. Currently pulling from 4 different spreadsheets and QuickBooks.",
        dashboardUsers: ["executives", "managers"],
        userCount: "6-20",
        dataSources: ["spreadsheets", "accounting", "crm"],
        keyMetrics: "Revenue per consultant, engagement margin %, utilization rate (target 75%), pipeline-to-close ratio, average engagement value, monthly burn rate, accounts receivable aging.",
        rbacNeeded: "yes",
        mobileAccess: "nice-to-have",
        dataRefresh: "daily",
        reportingExport: ["pdf-reports", "csv-export", "scheduled"],
      },
    },
    timeline: "3-6-months",
    budgetRange: "15k-30k",
    designPreference: "minimal",
    hasBrandAssets: "yes-full",
    brandColors: "Dark navy, white, and subtle blue accents.",
    competitorSites: "",
    inspirationSites: "datadog.com/dashboards — clean data visualization\nlinear.app — minimal but information-dense",
    additionalNotes: "Our partners spend Friday afternoons manually building reports from spreadsheets. We need real-time visibility into firm performance without the manual work. Must integrate with QuickBooks Online and our existing Salesforce CRM data.",
    howDidYouHear: "linkedin",
    preferredContact: "email",
  },

  // 13. Harbor Eats — ecommerce + landing page
  {
    selectedServices: ["ecommerce", "landing-page"],
    name: "Maya Chen",
    email: "maya@harboreats.com",
    phone: "206-555-0183",
    company: "Harbor Eats",
    industry: "food-hospitality",
    businessSize: "1-5",
    website: "",
    yearsInBusiness: "pre-launch",
    serviceAnswers: {
      ecommerce: {
        productType: ["physical", "subscriptions"],
        productCount: "11-50",
        sellInternational: "domestic-only",
        paymentMethods: ["credit-card", "apple-pay"],
        inventoryManagement: "yes-simple",
        shippingNeeds: ["flat-rate", "free-threshold", "local-pickup"],
        subscriptionBilling: "yes",
        productPhotos: "yes-some",
        returnsPolicy: "need-help",
      },
      "landing-page": {
        offerDescription: "Pre-launch landing page for Harbor Eats — curated artisan meal kits featuring Pacific Northwest ingredients. Subscribe weekly or order one-time. Launch special: 50% off first box.",
        desiredAction: "signup",
        trafficSource: ["facebook-ads", "social-organic", "email"],
        existingFunnel: "building",
        uniqueValue: "Every meal kit features ingredients sourced within 100 miles of Seattle. Recipes designed by local chefs. Supporting local farms and fisheries with every order.",
        socialProof: ["none"],
        abTesting: "yes",
      },
    },
    timeline: "asap",
    budgetRange: "5k-15k",
    designPreference: "organic",
    hasBrandAssets: "no",
    brandColors: "",
    competitorSites: "blueapron.com, sunbasket.com",
    inspirationSites: "dailyharvest.com — beautiful food photography and clean UX",
    additionalNotes: "Launching a meal kit subscription service focused on PNW ingredients. Need a landing page to capture pre-launch signups first, then a full e-commerce store by launch. We have about 500 people on a waitlist from Instagram.",
    howDidYouHear: "social-media",
    preferredContact: "email",
  },

  // 14. Evergreen Nonprofit — nonprofit, marketing website, unsure budget
  {
    selectedServices: ["marketing-website"],
    name: "Patricia Morrison",
    email: "patricia@evergreenconservancy.org",
    phone: "503-555-0156",
    company: "Evergreen Conservancy",
    industry: "nonprofit",
    businessSize: "1-5",
    website: "evergreenconservancy.org",
    yearsInBusiness: "6-10",
    serviceAnswers: {
      "marketing-website": {
        primaryOffering: "Environmental conservation nonprofit focused on old-growth forest preservation in the Pacific Northwest. We run community education programs, organize volunteer restoration events, and advocate for policy change.",
        targetAudience: "Environmentally conscious donors aged 30-65 in Oregon and Washington. Also grant foundations, corporate sponsors, and volunteers.",
        primaryCta: "learn",
        pageEstimate: "8-15",
        contentReady: "some",
        blogNeeded: "yes-regular",
        integrations: ["google-analytics", "email-marketing", "social", "payment"],
        seoFocus: "national",
        testimonialsReviews: "yes-few",
        competitorUrls: "nature.org — the trust factor\nonepercentfortheplanet.org — clean, mission-forward",
      },
    },
    timeline: "3-6-months",
    budgetRange: "unsure",
    designPreference: "nature-inspired",
    hasBrandAssets: "yes-partial",
    brandColors: "Forest green, earth brown, and cream.",
    competitorSites: "nature.org, sierraclub.org",
    inspirationSites: "patagonia.com — they make activism look beautiful",
    additionalNotes: "We just received a major grant and need to professionalize our web presence. Our current site was built by a volunteer 5 years ago. We need donor management integration (we use Bloomerang), volunteer signup forms, an events calendar, and a donation page that actually converts. Budget is TBD — we're applying for a tech capacity grant.",
    howDidYouHear: "conference",
    preferredContact: "email",
  },

  // 15. Apex Auto Detailing — landing page + website, ASAP
  {
    selectedServices: ["landing-page", "marketing-website"],
    name: "Tyrone Washington",
    email: "tyrone@apexautodetailing.com",
    phone: "404-555-0192",
    company: "Apex Auto Detailing",
    industry: "home-services",
    businessSize: "just-me",
    website: "",
    yearsInBusiness: "pre-launch",
    serviceAnswers: {
      "landing-page": {
        offerDescription: "Mobile auto detailing — we come to you. Interior/exterior packages starting at $99. Ceramic coating, paint correction, and fleet services also available.",
        desiredAction: "book-call",
        trafficSource: ["google-ads", "facebook-ads", "social-organic"],
        existingFunnel: "no",
        uniqueValue: "Mobile service — we come to your home or office. Eco-friendly products. Veteran-owned. Same-day availability.",
        socialProof: ["reviews", "numbers"],
        abTesting: "no",
      },
      "marketing-website": {
        primaryOffering: "Premium mobile auto detailing serving Metro Atlanta. Full interior/exterior detail, ceramic coating, paint correction, headlight restoration, and fleet services.",
        targetAudience: "Car enthusiasts and busy professionals in Metro Atlanta. People who care about their vehicles but don't have time to sit at a detail shop.",
        primaryCta: "book",
        pageEstimate: "1-3",
        contentReady: "no",
        blogNeeded: "no",
        integrations: ["google-analytics", "google-business", "booking", "payment"],
        seoFocus: "local",
        testimonialsReviews: "no",
        competitorUrls: "",
      },
    },
    timeline: "asap",
    budgetRange: "1k-5k",
    designPreference: "bold",
    hasBrandAssets: "no",
    brandColors: "",
    competitorSites: "",
    inspirationSites: "",
    additionalNotes: "Just left the military and starting my own business. Need a website and a landing page for my Google Ads campaign ASAP. Budget is tight but I'm ready to hustle.",
    howDidYouHear: "google-search",
    preferredContact: "phone",
  },

  // 16. Quantum Analytics — AI tools + dashboard, enterprise
  {
    selectedServices: ["ai-tools", "business-dashboard"],
    name: "Dr. Elena Vasquez",
    email: "elena@quantumanalytics.co",
    phone: "650-555-0204",
    company: "Quantum Analytics",
    industry: "technology",
    businessSize: "6-20",
    website: "quantumanalytics.co",
    yearsInBusiness: "3-5",
    serviceAnswers: {
      "ai-tools": {
        aiTaskDescription: "We need an AI-powered document analysis system. Our clients send us financial reports, SEC filings, and market research documents (PDFs, Word, Excel). We want AI to extract key metrics, identify trends, flag anomalies, and generate executive summaries automatically. Currently our analysts spend 60% of their time on data extraction instead of actual analysis.",
        aiDataSource: ["text-documents", "financial", "web-content"],
        aiUsers: ["internal-team", "clients"],
        aiErrorConsequence: "high-risk",
        humanReview: "always",
        aiIntegrations: "Must integrate with our existing data pipeline (Python/PostgreSQL), our client portal, and export to PowerPoint/PDF formats for client deliverables.",
        aiVolume: "101-1000",
      },
      "business-dashboard": {
        dashboardPurpose: "Client-facing analytics dashboards that visualize the insights our AI extracts. Each client gets their own dashboard with their data, trends, and AI-generated recommendations.",
        dashboardUsers: ["executives", "managers", "clients"],
        userCount: "50+",
        dataSources: ["database", "api"],
        keyMetrics: "Client-specific KPIs (varies by engagement), document processing volume, AI accuracy metrics, analysis turnaround time, client engagement metrics.",
        rbacNeeded: "yes",
        mobileAccess: "critical",
        dataRefresh: "realtime",
        reportingExport: ["pdf-reports", "csv-export", "custom"],
      },
    },
    timeline: "3-6-months",
    budgetRange: "30k+",
    designPreference: "data-rich",
    hasBrandAssets: "yes-full",
    brandColors: "Dark blue (#1E3A5F), electric blue (#00A8FF), white, and charcoal.",
    competitorSites: "palantir.com, alteryx.com",
    inspirationSites: "observable.com — beautiful data visualization\nlinear.app — clean, dense information design",
    additionalNotes: "We're a data analytics consultancy that's transitioning from purely manual analysis to AI-augmented workflows. This is our core product investment. The dashboard component is client-facing and needs to be white-labeled per client. We need SOC 2 compliance awareness in the architecture. Budget is flexible — this is a strategic investment.",
    howDidYouHear: "linkedin",
    preferredContact: "email",
  },

  // 17. Rosewood Dental — healthcare, website + portal + CRM
  {
    selectedServices: ["marketing-website", "client-portal", "crm-system"],
    name: "Dr. James Okonkwo",
    email: "james@rosewooddental.com",
    phone: "704-555-0138",
    company: "Rosewood Dental Practice",
    industry: "healthcare",
    businessSize: "6-20",
    website: "rosewooddental.com",
    yearsInBusiness: "6-10",
    serviceAnswers: {
      "marketing-website": {
        primaryOffering: "Full-service family and cosmetic dentistry — cleanings, crowns, implants, Invisalign, teeth whitening, pediatric dentistry. Two locations in Charlotte, NC.",
        targetAudience: "Families in the South Charlotte area, especially new residents. Also cosmetic dentistry patients who want premium services (veneers, implants, smile makeovers).",
        primaryCta: "book",
        pageEstimate: "8-15",
        contentReady: "some",
        blogNeeded: "yes-occasional",
        integrations: ["google-analytics", "google-business", "booking", "chat"],
        seoFocus: "local",
        testimonialsReviews: "yes-many",
        competitorUrls: "aspendental.com — too corporate\ncharlottedentist.com — good local SEO",
      },
      "client-portal": {
        portalPurpose: ["appointments", "documents", "invoices", "messaging"],
        currentClientComm: ["phone", "email"],
        documentSharing: "yes-download-only",
        paymentPortal: "yes",
        activeClientCount: "200+",
        portalBranding: "branded",
        portalIntegrations: "Dentrix (practice management), insurance verification, Stripe for patient payments",
      },
      "crm-system": {
        currentProcess: ["existing-crm", "email", "phone-notes"],
        contactVolume: "1000+",
        pipelineStages: "New Patient Lead → Appointment Booked → First Visit → Treatment Planned → Treatment In Progress → Completed → Recall/Maintenance",
        crmFeatures: ["pipeline", "notes", "tasks", "scheduling", "automation", "reporting"],
        crmIntegrations: ["email-provider", "calendar", "phone"],
        teamSize: "6-15",
        automationNeeds: "Recall reminders (6-month cleanings), treatment plan follow-ups, new patient welcome sequences, review request emails after appointments, birthday messages.",
      },
    },
    timeline: "3-6-months",
    budgetRange: "15k-30k",
    designPreference: "friendly",
    hasBrandAssets: "yes-full",
    brandColors: "Soft rose/mauve, white, and warm gray. Calming and premium.",
    competitorSites: "aspendental.com, charlottesmilecenter.com",
    inspirationSites: "tenderdental.com — warm and approachable for a dental practice",
    additionalNotes: "We're opening our second location next quarter and need a professional web presence that serves both. Our front desk spends too much time on the phone confirming appointments and chasing down treatment plan approvals. We need automation badly. We have 800+ Google reviews at 4.9 stars — we want to showcase those prominently.",
    howDidYouHear: "referral",
    preferredContact: "phone",
  },

  // 18. Wildfire Creative Agency — full platform, comprehensive
  {
    selectedServices: ["full-platform"],
    name: "Kai Nakamura",
    email: "kai@wildfirecreative.co",
    phone: "971-555-0129",
    company: "Wildfire Creative Agency",
    industry: "professional-services",
    businessSize: "6-20",
    website: "wildfirecreative.co",
    yearsInBusiness: "3-5",
    serviceAnswers: {
      "full-platform": {
        businessProcesses: ["client-management", "project-tracking", "invoicing", "scheduling", "team-management", "reporting", "communication"],
        platformTeamSize: "6-20",
        currentTools: "Notion for project management, HubSpot free CRM, Wave for invoicing, Calendly for scheduling, Slack for internal comms, Google Drive for file sharing. None of these talk to each other.",
        biggestPainPoint: "Client onboarding takes 2 weeks because it involves 7 different tools and manual data entry between each one. We lose at least 1 project/quarter because onboarding was so slow the client went elsewhere.",
        clientFacing: "yes-essential",
        billingNeeds: ["create-invoices", "online-payment", "recurring", "estimates"],
        automationPriorities: "Client onboarding (kick-off email, questionnaire, contract, invoice — all triggered automatically). Project milestone notifications to clients. Automatic invoicing based on project phase completion. Weekly internal status reports.",
        migrationData: "yes-some",
      },
    },
    timeline: "1-3-months",
    budgetRange: "30k+",
    designPreference: "creative",
    hasBrandAssets: "yes-full",
    brandColors: "Flame orange, charcoal, and white. Bold and energetic.",
    competitorSites: "functionpoint.com, productive.io",
    inspirationSites: "linear.app — the speed and simplicity\nnotion.so — the flexibility and aesthetics",
    additionalNotes: "We're a branding and web design agency that's great at building tools for clients but terrible at using our own. The irony is painful. We need a unified operations platform that handles the full client lifecycle from lead to completed project to ongoing retainer. Must be fast — our team hates slow tools.",
    howDidYouHear: "linkedin",
    preferredContact: "email",
  },

  // 19. Fresh Start Cleaning — greenfield, marketing website, unsure budget
  {
    selectedServices: ["marketing-website"],
    name: "Ashley Brooks",
    email: "ashley@freshstartcleans.com",
    phone: "678-555-0174",
    company: "Fresh Start Cleaning Services",
    industry: "home-services",
    businessSize: "just-me",
    website: "",
    yearsInBusiness: "pre-launch",
    serviceAnswers: {
      "marketing-website": {
        primaryOffering: "Residential cleaning services — weekly, biweekly, and deep cleaning for homes and apartments in Metro Atlanta.",
        targetAudience: "Busy professionals and families in Metro Atlanta who need a reliable, trustworthy cleaning service.",
        primaryCta: "form",
        pageEstimate: "1-3",
        contentReady: "no",
        blogNeeded: "unsure",
        integrations: ["google-business"],
        seoFocus: "local",
        testimonialsReviews: "no",
        competitorUrls: "",
      },
    },
    timeline: "flexible",
    budgetRange: "unsure",
    designPreference: "let-us-decide",
    hasBrandAssets: "no",
    brandColors: "",
    competitorSites: "",
    inspirationSites: "",
    additionalNotes: "Just starting out. I've been cleaning for friends and family and everyone says I should start a business. I don't know much about websites but I know I need one.",
    howDidYouHear: "google-search",
    preferredContact: "phone",
  },

  // 20. Pinnacle Financial — website + dashboard + CRM
  {
    selectedServices: ["marketing-website", "business-dashboard", "crm-system"],
    name: "Michael Harrington",
    email: "mharrington@pinnaclefa.com",
    phone: "617-555-0201",
    company: "Pinnacle Financial Advisors",
    industry: "professional-services",
    businessSize: "6-20",
    website: "pinnaclefa.com",
    yearsInBusiness: "10+",
    serviceAnswers: {
      "marketing-website": {
        primaryOffering: "Independent wealth management firm — retirement planning, investment management, tax optimization, estate planning, and business succession planning. Fee-only fiduciary advisors. $500K minimum AUM.",
        targetAudience: "High-net-worth individuals and families in Greater Boston with $500K-$10M in investable assets. Also business owners planning succession or sale.",
        primaryCta: "form",
        pageEstimate: "8-15",
        contentReady: "some",
        blogNeeded: "yes-regular",
        integrations: ["google-analytics", "email-marketing", "chat"],
        seoFocus: "specific-keywords",
        testimonialsReviews: "yes-few",
        competitorUrls: "creativeplanning.com — modern for financial services\nfisher401k.com — strong content marketing",
      },
      "business-dashboard": {
        dashboardPurpose: "Internal firm management — AUM tracking, client portfolio performance overview, revenue by advisor, client acquisition funnel metrics, compliance deadline tracking.",
        dashboardUsers: ["executives", "managers"],
        userCount: "1-5",
        dataSources: ["spreadsheets", "api", "accounting"],
        keyMetrics: "Total AUM, net new assets, client retention rate, revenue per advisor, average account size, client satisfaction (NPS), compliance audit status.",
        rbacNeeded: "yes",
        mobileAccess: "nice-to-have",
        dataRefresh: "daily",
        reportingExport: ["pdf-reports", "csv-export"],
      },
      "crm-system": {
        currentProcess: ["spreadsheets", "email", "existing-crm"],
        contactVolume: "201-1000",
        pipelineStages: "Prospect → Discovery Meeting → Financial Plan Presentation → Commitment → Onboarding → Active Client → Annual Review → Referral Cultivation",
        crmFeatures: ["pipeline", "notes", "email-integration", "tasks", "scheduling", "reporting", "automation"],
        crmIntegrations: ["email-provider", "calendar", "accounting", "marketing"],
        teamSize: "6-15",
        automationNeeds: "Annual review scheduling reminders, birthday/anniversary acknowledgments, market update email sequences, quarterly performance report distribution, new client welcome drip campaign, referral follow-ups.",
      },
    },
    timeline: "3-6-months",
    budgetRange: "15k-30k",
    designPreference: "sophisticated",
    hasBrandAssets: "yes-full",
    brandColors: "Deep green (#1B4D3E), gold, and white. Trust and prestige.",
    competitorSites: "creativeplanning.com, northwesternmutual.com",
    inspirationSites: "stripe.com — clean professionalism\nwealthfront.com — modern fintech feel applied to traditional wealth management",
    additionalNotes: "We're an SEC-registered RIA firm with $250M AUM. Our current site is from 2018 and makes us look dated compared to robo-advisors. We lose prospects to firms with better digital presence despite having better advisors. Our Salesforce license is up in 4 months and we want to replace it with something purpose-built. Compliance considerations are critical — SEC advertising rules apply to everything we publish.",
    howDidYouHear: "referral",
    preferredContact: "email",
  },
];

// ---------------------------------------------------------------------------
// Seed Runner
// ---------------------------------------------------------------------------

async function seedIntakes() {
  const now = Date.now();
  const DAY = 86400000;

  // Spread submissions over the last 30 days for realistic date distribution
  const offsets = [
    28, 26, 24, 22, 20, 18, 17, 15, 14, 12,
    11, 9, 8, 7, 6, 5, 4, 3, 2, 1,
  ];

  let seeded = 0;

  for (let i = 0; i < intakes.length; i++) {
    const submittedAt = new Date(now - offsets[i] * DAY).toISOString();
    const analysis = analyzeIntake(intakes[i], { submittedAt });

    const primaryRec = analysis.serviceRecommendations.find(
      (r) => r.isPrimary,
    );

    await db.insert(schema.intakeSubmissions).values({
      id: analysis.id,
      submittedAt: new Date(analysis.submittedAt),
      name: analysis.formData.name,
      email: analysis.formData.email.toLowerCase(),
      company: analysis.formData.company,
      complexityScore: analysis.complexityScore.overall,
      primaryService: primaryRec?.serviceTitle ?? null,
      formData: analysis.formData,
      analysis: analysis,
    });

    seeded++;
    const label = analysis.complexityScore.label.padEnd(10);
    const score = String(analysis.complexityScore.overall).padStart(2);
    // eslint-disable-next-line no-console
    console.log(
      `  [${seeded}/20] ${label} (${score}/10) — ${analysis.formData.company} — ${primaryRec?.serviceTitle ?? "N/A"}`,
    );
  }

  // eslint-disable-next-line no-console
  console.log(`\nSeeded ${seeded} intake submissions.`);
  await pool.end();
}

seedIntakes().catch((err) => {
  // eslint-disable-next-line no-console
  console.error("Seed failed:", err);
  process.exit(1);
});
